Felix Greifeneder Model Validation

In [ ]:
#pip install ../../../F_pysmm/pysmm_v02.zip

In [1]:
# PYthon Sentinel-1 soil-Moisture Mapping Toolbox (PYSMM)
import pysmm
from pysmm.derive_SM import get_ts
from pysmm.derive_SM import get_map
import os
import geopandas as gpd
import pandas as pd
import ee

In [2]:
# Trigger the authentication flow.
ee.Authenticate()


Successfully saved authorization token.


In [ ]:
from pysmm.derive_SM import get_map
#output_dir = "./GM"

#os.makedirs(output_dir,exist_ok=True)

# get_map(10.582923880778253,46.651038714674115,10.758705130778253, 46.76855750461985,
#         outpath='Pysmm_SMC_pred',
#         sampling=20,                             # specify desired output resolution
#         year=None, month=None, day=None,        # define a date (optional)
#         #tracknr=168,                           # define the Sentinel-1 track (optinal)
#         overwrite=False,
#         start='2020-06-01',
#         stop='2020-06-05')

get_map(9.2098876189069827,45.5898599951793599, 13.1200743876224362,47.7767187228399237,
        outpath='Pysmm_SMC_pred',
        sampling=20,                             # specify desired output resolution
        year=None, month=None, day=None,        # define a date (optional)
        #tracknr=168,                           # define the Sentinel-1 track (optinal)
        overwrite=False,
        start='2023-04-29',
        stop='2023-05-06')

To derive the soil moisture time-series of a single location use get_ts():

In [ ]:
# Read the shapefile
Italy_Stations = gpd.read_file("../02_Data/03_Vector_data/Station_coordinates.shp")
# Sites ID

ID_Site = Italy_Stations['Station na']# Adding NEPAS SITE
#ID_Site=ID_Site.append(pd.Series("NEPAS",index=[len(ID_Site)])) 
# Sites coordinates
x=Italy_Stations.geometry.x
y=Italy_Stations.geometry.y

# List of tuples
Sites = []
for i in range(len(x)):
    Sites.append((x[i],y[i]))
# Coordinates of NEPAS Site 
#Sites.append(tuple((12.272601,46.807186,)))

In [3]:
ID_Site=["Dresdner Hütte","Weisssee","Leutasch","Obergurgl/Hohe Mut","Corvara"]

In [4]:
Sites=[(11.139570862940008, 46.99741143588636),(10.714437, 46.872909),(11.161770 ,47.375715),(11.03058911753006,46.84864073381656),( 11.899888,46.544487)]

In [ ]:
Sites


In [5]:
output_dir = "../02_Data/04_SMC_Estimations/get_ts/Neutrino_stations"
os.makedirs(output_dir,exist_ok=True)
footprints = [20,50,100,200,500]
for f in footprints:
    footprint_dir = f'{output_dir}/{f}/'
    os.makedirs(footprint_dir,exist_ok=True)   
    for i in range(0,len(Sites),1): 
        print(f'SiteID_{ID_Site[i]}_{f}_m')
        try:
            print(f'(SiteID_{ID_Site[i]})')
            get_ts(loc=Sites[i],
                        workpath=footprint_dir,
                        tracknr=None,
                        footprint=f,
                        calc_anomalies=False,
                        create_plots=False,
                        names=None,
                        export_csv=f'SiteID_{ID_Site[i]}_{f}_m_'
                        )
        except: 
            pass

SiteID_Dresdner Hütte_20_m
(SiteID_Dresdner Hütte)
Estimating surface soil moisture for lon: 11.139570862940008 lat: 46.99741143588636
Extracting data from 4 Sentinel-1 tracks...
[ 95 117 168 170]
Time-series extraction finished in      27.78seconds


c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DummyRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator GradientBoostingRegressor from vers

Estimation for track #170 not possible - time-series too short
SiteID_Weisssee_20_m
(SiteID_Weisssee)
Estimating surface soil moisture for lon: 10.714437 lat: 46.872909
Extracting data from 4 Sentinel-1 tracks...
[ 15 117 168 170]
Time-series extraction finished in      26.18seconds


c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DummyRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator GradientBoostingRegressor from vers

SiteID_Leutasch_20_m
(SiteID_Leutasch)
Estimating surface soil moisture for lon: 11.16177 lat: 47.375715
Extracting data from 4 Sentinel-1 tracks...
[ 95 117 168 170]
Time-series extraction finished in      23.35seconds


c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DummyRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator GradientBoostingRegressor from vers

Estimation for track #170 not possible - time-series too short
SiteID_Obergurgl/Hohe Mut_20_m
(SiteID_Obergurgl/Hohe Mut)
Estimating surface soil moisture for lon: 11.03058911753006 lat: 46.84864073381656
Extracting data from 4 Sentinel-1 tracks...
[ 95 117 168 170]
Time-series extraction finished in      23.15seconds


c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DummyRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator GradientBoostingRegressor from vers

Estimation for track #170 not possible - time-series too short
SiteID_Corvara_20_m
(SiteID_Corvara)
Estimating surface soil moisture for lon: 11.899888 lat: 46.544487
Extracting data from 5 Sentinel-1 tracks...
[ 44  95 117 168 170]
Time-series extraction finished in      34.41seconds


c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DummyRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator GradientBoostingRegressor from vers

Estimation for track #170 not possible - time-series too short
SiteID_Dresdner Hütte_50_m
(SiteID_Dresdner Hütte)
Estimating surface soil moisture for lon: 11.139570862940008 lat: 46.99741143588636
Extracting data from 4 Sentinel-1 tracks...
[ 95 117 168 170]
Time-series extraction finished in      26.06seconds


c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DummyRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator GradientBoostingRegressor from vers

Estimation for track #170 not possible - time-series too short
SiteID_Weisssee_50_m
(SiteID_Weisssee)
Estimating surface soil moisture for lon: 10.714437 lat: 46.872909
Extracting data from 4 Sentinel-1 tracks...
[ 15 117 168 170]
Time-series extraction finished in      24.65seconds


c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DummyRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator GradientBoostingRegressor from vers

SiteID_Leutasch_50_m
(SiteID_Leutasch)
Estimating surface soil moisture for lon: 11.16177 lat: 47.375715
Extracting data from 4 Sentinel-1 tracks...
[ 95 117 168 170]
Time-series extraction finished in      20.89seconds


c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DummyRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator GradientBoostingRegressor from vers

Estimation for track #170 not possible - time-series too short
SiteID_Obergurgl/Hohe Mut_50_m
(SiteID_Obergurgl/Hohe Mut)
Estimating surface soil moisture for lon: 11.03058911753006 lat: 46.84864073381656
Extracting data from 4 Sentinel-1 tracks...
[ 95 117 168 170]
Time-series extraction finished in      21.98seconds


c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DummyRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator GradientBoostingRegressor from vers

Estimation for track #170 not possible - time-series too short
SiteID_Corvara_50_m
(SiteID_Corvara)
Estimating surface soil moisture for lon: 11.899888 lat: 46.544487
Extracting data from 5 Sentinel-1 tracks...
[ 44  95 117 168 170]
Time-series extraction finished in      31.87seconds


c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DummyRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator GradientBoostingRegressor from vers

Estimation for track #170 not possible - time-series too short
SiteID_Dresdner Hütte_100_m
(SiteID_Dresdner Hütte)
Estimating surface soil moisture for lon: 11.139570862940008 lat: 46.99741143588636
Extracting data from 4 Sentinel-1 tracks...
[ 95 117 168 170]
Time-series extraction finished in      27.95seconds


c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DummyRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator GradientBoostingRegressor from vers

Estimation for track #170 not possible - time-series too short
SiteID_Weisssee_100_m
(SiteID_Weisssee)
Estimating surface soil moisture for lon: 10.714437 lat: 46.872909
Extracting data from 4 Sentinel-1 tracks...
[ 15 117 168 170]
Time-series extraction finished in      29.29seconds


c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DummyRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator GradientBoostingRegressor from vers

SiteID_Leutasch_100_m
(SiteID_Leutasch)
Estimating surface soil moisture for lon: 11.16177 lat: 47.375715
Extracting data from 4 Sentinel-1 tracks...
[ 95 117 168 170]
Time-series extraction finished in      19.69seconds


c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DummyRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator GradientBoostingRegressor from vers

Estimation for track #170 not possible - time-series too short
SiteID_Obergurgl/Hohe Mut_100_m
(SiteID_Obergurgl/Hohe Mut)
Estimating surface soil moisture for lon: 11.03058911753006 lat: 46.84864073381656
Extracting data from 4 Sentinel-1 tracks...
[ 95 117 168 170]
Time-series extraction finished in      19.87seconds


c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DummyRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator GradientBoostingRegressor from vers

Estimation for track #170 not possible - time-series too short
SiteID_Corvara_100_m
(SiteID_Corvara)
Estimating surface soil moisture for lon: 11.899888 lat: 46.544487
Extracting data from 5 Sentinel-1 tracks...
[ 44  95 117 168 170]
Time-series extraction finished in      36.30seconds


c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DummyRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator GradientBoostingRegressor from vers

Estimation for track #170 not possible - time-series too short
SiteID_Dresdner Hütte_200_m
(SiteID_Dresdner Hütte)
Estimating surface soil moisture for lon: 11.139570862940008 lat: 46.99741143588636
Extracting data from 4 Sentinel-1 tracks...
[ 95 117 168 170]
Time-series extraction finished in      26.33seconds


c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DummyRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator GradientBoostingRegressor from vers

Estimation for track #170 not possible - time-series too short
SiteID_Weisssee_200_m
(SiteID_Weisssee)
Estimating surface soil moisture for lon: 10.714437 lat: 46.872909
Extracting data from 4 Sentinel-1 tracks...
[ 15 117 168 170]
Time-series extraction finished in      27.84seconds


c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DummyRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator GradientBoostingRegressor from vers

SiteID_Leutasch_200_m
(SiteID_Leutasch)
Estimating surface soil moisture for lon: 11.16177 lat: 47.375715
Extracting data from 4 Sentinel-1 tracks...
[ 95 117 168 170]
Time-series extraction finished in      21.81seconds


c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DummyRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator GradientBoostingRegressor from vers

Estimation for track #170 not possible - time-series too short
SiteID_Obergurgl/Hohe Mut_200_m
(SiteID_Obergurgl/Hohe Mut)
Estimating surface soil moisture for lon: 11.03058911753006 lat: 46.84864073381656
Extracting data from 4 Sentinel-1 tracks...
[ 95 117 168 170]
Time-series extraction finished in      20.94seconds


c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DummyRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator GradientBoostingRegressor from vers

Estimation for track #170 not possible - time-series too short
SiteID_Corvara_200_m
(SiteID_Corvara)
Estimating surface soil moisture for lon: 11.899888 lat: 46.544487
Extracting data from 5 Sentinel-1 tracks...
[ 44  95 117 168 170]
Time-series extraction finished in      36.81seconds


c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DummyRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator GradientBoostingRegressor from vers

Estimation for track #170 not possible - time-series too short
SiteID_Dresdner Hütte_500_m
(SiteID_Dresdner Hütte)
Estimating surface soil moisture for lon: 11.139570862940008 lat: 46.99741143588636
Extracting data from 4 Sentinel-1 tracks...
[ 95 117 168 170]
Time-series extraction finished in      25.21seconds


c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DummyRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator GradientBoostingRegressor from vers

Estimation for track #170 not possible - time-series too short
SiteID_Weisssee_500_m
(SiteID_Weisssee)
Estimating surface soil moisture for lon: 10.714437 lat: 46.872909
Extracting data from 4 Sentinel-1 tracks...
[ 15 117 168 170]
Time-series extraction finished in      25.01seconds


c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DummyRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator GradientBoostingRegressor from vers

Estimation for track #170 not possible - time-series too short
SiteID_Leutasch_500_m
(SiteID_Leutasch)
Estimating surface soil moisture for lon: 11.16177 lat: 47.375715
Extracting data from 4 Sentinel-1 tracks...
[ 95 117 168 170]
Time-series extraction finished in      23.93seconds


c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DummyRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator GradientBoostingRegressor from vers

Estimation for track #170 not possible - time-series too short
SiteID_Obergurgl/Hohe Mut_500_m
(SiteID_Obergurgl/Hohe Mut)
Estimating surface soil moisture for lon: 11.03058911753006 lat: 46.84864073381656
Extracting data from 4 Sentinel-1 tracks...
[ 95 117 168 170]
Time-series extraction finished in      23.15seconds


c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DummyRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator GradientBoostingRegressor from vers

Estimation for track #170 not possible - time-series too short
SiteID_Corvara_500_m
(SiteID_Corvara)
Estimating surface soil moisture for lon: 11.899888 lat: 46.544487
Extracting data from 5 Sentinel-1 tracks...
[ 44  95 117 168 170]
Time-series extraction finished in      35.64seconds


c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DummyRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator GradientBoostingRegressor from vers

Estimation for track #170 not possible - time-series too short


c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\pysmm\GEE_wrappers.py:1214: FutureWarning: Value based partial slicing on non-monotonic DatetimeIndexes with non-existing keys is deprecated and will raise a KeyError in a future Version.
  med_vol = np.median(g0vol_ts_lin.loc['2015-01-01':'2020-12-31'])
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\pysmm\GEE_wrappers.py:1216: FutureWarning: Value based partial slicing on non-monotonic DatetimeIndexes with non-existing keys is deprecated and will raise a KeyError in a future Version.
  l8b4_med = np.median(l8b4.loc['2015-01-01':'2020-12-31'])
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows\lib\site-packages\pysmm\GEE_wrappers.py:1217: FutureWarning: Value based partial slicing on non-monotonic DatetimeIndexes with non-existing keys is deprecated and will raise a KeyError in a future Version.
  l8b5_med = np.median(l8b5.loc['2015-01-01':'2020-12-31'])
c:\Users\franc\anaconda3\envs\Curso_PDIS_Windows

In [ ]:
output_dir = "../02_Data/04_SMC_Estimations/get_ts/Neutrino_stations"
os.makedirs(output_dir,exist_ok=True)
f=50
footprint_dir = f'{output_dir}/{f}/'
get_ts(loc=Sites,
    workpath=footprint_dir,
    tracknr=None,
    footprint=f,
    calc_anomalies=False,
    create_plots=False,
    names=None,
    export_csv=f'SiteID_{f}_m_'
    )